package edu.washington.cs.lavatorylocator.view;

import edu.washington.cs.lavatorylocator.R;
import edu.washington.cs.lavatorylocator.model.LavatoryData;
import android.content.Context;
import android.view.LayoutInflater;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.TextView;

public class LavatorySearchResultsListItemView extends RelativeLayout {

    private TextView lavatoryNameTextView;
    private RatingBar averageRatingBar;
    private TextView reviewCountTextView;
    private TextView floorTextView;

    public LavatorySearchResultsListItemView(Context context) {
        super(context);
        inflateView(context);
    }

    private void inflateView(Context context) {
        LayoutInflater.from(context).inflate(R.layout.search_result_item, this);

        lavatoryNameTextView = ((TextView) findViewById(R.id.search_result_item_lavatory_name));
        averageRatingBar = ((RatingBar) findViewById(R.id.search_result_item_average_review));
        reviewCountTextView = ((TextView) findViewById(R.id.search_result_item_review_count));
        floorTextView = ((TextView) findViewById(R.id.search_result_item_floor));
    }

    public void updateView(LavatoryData lavatoryData) {
        // TODO: replace with the name generated by the server
        lavatoryNameTextView.setText(lavatoryData.getBuilding() + " "
                + lavatoryData.getLid() + " " + lavatoryData.getType());

        averageRatingBar.setRating((float) lavatoryData.getAvgRating());

        // need to convert the count into a String; otherwise it is mistaken for
        // a resource id
        reviewCountTextView.setText(Integer.toString(lavatoryData.getReviewCount()));
        floorTextView.setText(lavatoryData.getFloor());
    }
}
